[package]
name = "nds"
version = "0.1.0"
authors = ["Lucas Reynolds <lreynolds18@gmail.com>"]

[dependencies]
piston = "0.34.0"
piston2d-graphics = "0.22.0"
pistoncore-glutin_window = "0.40.0"
piston2d-opengl_graphics = "0.47.0"
